#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
seo_audit.py — Automated SEO/AdSense/Search Console health check + auto-fix

Runs BEFORE build.py (or right after) in the GitHub Actions pipeline.

What it fixes (automatically, safely):
---------------------------------------
1. CANONICAL URL INCONSISTENCY
   Google Search Console flags "Page with redirect" when the canonical in
   a page's <head> differs from the actual URL Google crawled. Common cause:
   some pages have canonical = "https://thestreamic.in/..." (apex) while
   the site canonical is "https://www.thestreamic.in/..." (www). The
   apex→www redirect creates the "Page with redirect" error.
   FIX: rewrite every canonical link tag in docs/**.html to use CANONICAL_HOST.

2. MIXED URL FORMS IN HTML
   Any <a href="http://thestreamic.in/...">, <a href="https://thestreamic.in/...">
   (apex) that should be www — rewritten to canonical form.

3. SITEMAP HYGIENE
   Verifies sitemap.xml exists, uses canonical host, and has no trailing
   /index.html entries (which cause duplicate-index warnings).

4. ROBOTS.TXT VALIDATION
   Confirms robots.txt points at the canonical sitemap URL.

5. MISSING ADSENSE META
   Adds <meta name="google-adsense-account" content="..."> to every page's
   <head> if missing (recommended for AdSense auto-ads verification).
   Only applies when ADSENSE_PUB_ID env var is set.

6. UNREACHABLE FILES (404s)
   Scans sitemap.xml for URLs whose corresponding docs/ file doesn't exist.
   Reports (doesn't auto-delete — that's a human decision).

Non-destructive, idempotent, safe to re-run.
No external API calls. No network writes. Exits 0 even on soft failures.

Wire-up (ONE line in .github/workflows/build.yml, right before build.py):

    - name: SEO audit + auto-fix
      run: python scripts/seo_audit.py || echo "SEO audit skipped"

That's all. The script writes a report to stdout + fixes canonical URLs
in place. Re-running it is a no-op if everything is already clean.
"""
import os
import re
import sys
from pathlib import Path

ROOT            = Path(__file__).resolve().parent.parent
DOCS            = ROOT / "docs"
SITEMAP         = DOCS / "sitemap.xml"
ROBOTS          = DOCS / "robots.txt"
CANONICAL_HOST  = "https://www.thestreamic.in"   # the one true URL root
ADSENSE_PUB_ID  = os.environ.get("ADSENSE_PUB_ID", "")  # e.g. "ca-pub-8033069131874524"

# Alternate hostname forms that MUST be rewritten to CANONICAL_HOST
_ALIAS_FORMS = [
    "http://www.thestreamic.in",
    "http://thestreamic.in",
    "https://thestreamic.in",   # apex without www — the main offender
]


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except Exception:
        return ""


def _write(path: Path, content: str) -> bool:
    try:
        path.write_text(content, encoding="utf-8")
        return True
    except Exception as e:
        print(f"    [ERROR] Could not write {path}: {e}")
        return False


# ── FIX 1 + 2: canonical URL + internal link rewriting ────────────────────────

def fix_canonical_urls() -> tuple:
    """Rewrite every alias host form to CANONICAL_HOST in every HTML file."""
    fixed_files = 0
    total_rewrites = 0
    html_files = list(DOCS.rglob("*.html"))
    for fp in html_files:
        original = _read(fp)
        if not original:
            continue
        patched = original
        local_rewrites = 0
        for alias in _ALIAS_FORMS:
            if alias in patched:
                # Count before replacing so we report accurately.
                count = patched.count(alias)
                patched = patched.replace(alias, CANONICAL_HOST)
                local_rewrites += count
        if local_rewrites > 0:
            if _write(fp, patched):
                fixed_files += 1
                total_rewrites += local_rewrites
                rel = fp.relative_to(ROOT)
                print(f"    ✓ {rel}: {local_rewrites} URL(s) rewritten to canonical")
    return fixed_files, total_rewrites


# ── FIX 3: sitemap hygiene ────────────────────────────────────────────────────

def audit_sitemap() -> list:
    """Return list of issues found in sitemap.xml (does NOT rewrite —
    sitemap is generated by build.py, so fixes belong there)."""
    issues = []
    if not SITEMAP.exists():
        issues.append(f"sitemap.xml missing at {SITEMAP}")
        return issues
    content = _read(SITEMAP)
    # Wrong host
    for alias in _ALIAS_FORMS:
        if alias in content:
            count = content.count(alias)
            issues.append(f"sitemap has {count} entries using alias {alias} — should be {CANONICAL_HOST}")
    # Duplicate index.html entries
    if "/index.html</loc>" in content and "<loc>" + CANONICAL_HOST + "/</loc>" in content:
        issues.append("sitemap has both / and /index.html — risks duplicate-index warning")
    # URL count
    url_count = content.count("<url>")
    print(f"    sitemap URL count: {url_count}")
    return issues


# ── FIX 4: robots.txt sanity ──────────────────────────────────────────────────

def audit_robots() -> list:
    issues = []
    if not ROBOTS.exists():
        issues.append("robots.txt missing")
        return issues
    content = _read(ROBOTS)
    if "Sitemap:" not in content:
        issues.append("robots.txt has no Sitemap: directive")
    elif CANONICAL_HOST not in content:
        issues.append(f"robots.txt Sitemap: line does not use {CANONICAL_HOST}")
    return issues


# ── FIX 5: AdSense meta injection (only if pub ID provided) ───────────────────

_ADSENSE_META_RE = re.compile(
    r'<meta\s+name="google-adsense-account"\s+content="[^"]*"\s*/?>',
    re.IGNORECASE,
)

def ensure_adsense_meta() -> tuple:
    if not ADSENSE_PUB_ID:
        return 0, 0
    target_tag = f'<meta name="google-adsense-account" content="{ADSENSE_PUB_ID}">'
    files_patched = 0
    already_ok = 0
    for fp in DOCS.rglob("*.html"):
        content = _read(fp)
        if not content:
            continue
        if _ADSENSE_META_RE.search(content):
            already_ok += 1
            continue
        # Insert just before </head>
        if "</head>" in content:
            new = content.replace("</head>", f"  {target_tag}\n</head>", 1)
            if _write(fp, new):
                files_patched += 1
    return files_patched, already_ok


# ── FIX 6: find sitemap URLs whose local file is missing ──────────────────────

def find_broken_sitemap_entries() -> list:
    broken = []
    if not SITEMAP.exists():
        return broken
    content = _read(SITEMAP)
    url_pattern = re.compile(
        r"<loc>" + re.escape(CANONICAL_HOST) + r"(/[^<]*)</loc>"
    )
    for match in url_pattern.finditer(content):
        path = match.group(1)
        # Root "/" maps to docs/index.html
        if path == "/" or path == "":
            check = DOCS / "index.html"
        elif path.endswith("/"):
            check = DOCS / path.lstrip("/") / "index.html"
        else:
            check = DOCS / path.lstrip("/")
        if not check.exists():
            broken.append(f"{CANONICAL_HOST}{path}  →  {check.relative_to(ROOT)} not found")
    return broken


# ── MAIN ──────────────────────────────────────────────────────────────────────

def main() -> int:
    print("=== seo_audit.py — Streamic SEO health check ===")
    print(f"  Canonical host: {CANONICAL_HOST}")
    print(f"  Docs root:      {DOCS}")
    print()

    if not DOCS.exists():
        print("  ⚠ docs/ directory missing — has build.py run yet?")
        return 0

    # Fix canonical URLs in HTML
    print("[1] Canonical URL rewrites in HTML files...")
    files, rewrites = fix_canonical_urls()
    if rewrites:
        print(f"    ✓ {files} file(s) patched, {rewrites} URL(s) rewritten")
    else:
        print("    ✓ All HTML files already use canonical host")
    print()

    # Sitemap audit
    print("[2] Sitemap hygiene...")
    sm_issues = audit_sitemap()
    if sm_issues:
        for i in sm_issues:
            print(f"    ⚠ {i}")
    else:
        print("    ✓ sitemap.xml looks healthy")
    print()

    # Robots audit
    print("[3] robots.txt...")
    r_issues = audit_robots()
    if r_issues:
        for i in r_issues:
            print(f"    ⚠ {i}")
    else:
        print("    ✓ robots.txt looks healthy")
    print()

    # AdSense meta
    print("[4] AdSense verification meta tag...")
    if not ADSENSE_PUB_ID:
        print("    (skipped — set ADSENSE_PUB_ID env var to enable)")
    else:
        patched, ok = ensure_adsense_meta()
        print(f"    ✓ {ok} files already tagged, {patched} newly patched")
    print()

    # Broken sitemap entries
    print("[5] Broken sitemap URLs (files not on disk)...")
    broken = find_broken_sitemap_entries()
    if broken:
        print(f"    ⚠ {len(broken)} URL(s) in sitemap with no backing file:")
        for b in broken[:20]:
            print(f"      {b}")
        if len(broken) > 20:
            print(f"      ... and {len(broken) - 20} more")
    else:
        print("    ✓ All sitemap URLs have corresponding files")
    print()

    print("=== seo_audit complete ===")
    return 0


if __name__ == "__main__":
    sys.exit(main())
